apiVersion: v1
kind: ConfigMap
metadata:
  name: eks-cicd-demo-config
  namespace: production
  labels:
    app: eks-cicd-demo
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
  LOG_LEVEL: "INFO"
