server:
  port: 8080

spring:
  application:
    name: aws-eks-cicd-demo

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.devops.demo: DEBUG
